# Generated by Django 4.2 on 2023-04-07 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_form', models.PositiveSmallIntegerField()),
                ('form_name', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=255)),
                ('channel_id', models.CharField(max_length=25)),
                ('urls_pictures', models.TextField(max_length=500)),
                ('text', models.TextField(max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'form to send',
                'verbose_name_plural': 'forms to send',
            },
        ),
    ]
