# Generated by Django 4.2 on 2023-04-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlarray',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL of picture'),
        ),
    ]
