# Generated by Django 4.1.7 on 2023-04-02 21:20

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
    ]
