# Generated by Django 4.2 on 2023-04-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='send_delay',
            field=models.PositiveIntegerField(default=60, verbose_name='sanding delay'),
        ),
    ]
